all : program3.o strfunctions.o
	gcc -w program3.o strfunctions.o -o program3
	./program3

program3.o:
	gcc -w -g -c program3.c -o program3.o

strfunctions.o:
	gcc -w -g -c strfunctions.c -o strfunctions.o 
